name: mosdef37
channels:
  - conda-forge
  - mosdef
  - bioconda
  - omnia
dependencies:
  - python=3.7
  - pip
  - matplotlib
  - numpy
  - unyt >= 2.4
  - boltons
  - lxml
  - parmed
  - foyer
  - mbuild>=0.10.6
  - openbabel
  - py3Dmol
  - ambertools
  - panedr
  - nodejs>=10
  - jupyterlab
  - ipywidgets
  - pip:
    - "--editable=git+https://github.com/rsdefever/GAFF-foyer.git#egg=gaff_foyer-master"
    - "--editable=git+https://github.com/rsdefever/antefoyer.git#egg=antefoyer-master"
    - "--editable=git+https://github.com/mosdef-hub/gmso.git#egg=gmso-master"
